font=FiraCode Nerd Font:size=14
use-bold=yes
prompt="> "
placeholder=Search Tom's Thinkcentre...
icon-theme=default
icons-enabled=yes
horizontal-pad=20

# flavours start
[colors]
background=000f05e6
text=dbffdbff
prompt=dbffdbff
placeholder=40986080
input=dbffdbff
match=f13a44ff
selection=dbffdbff
selection-text=000f05ff
selection-match=f13a44ff
border=80c884ff
# flavours end

[border]
width=2
radius=5

[key-bindings]
# cancel=Escape Control+g Control+c Control+bracketleft
# execute=Return KP_Enter Control+y
next=Down Control+j
# execute-input=Shift+Return Shift+KP_Enter
cursor-left=none
# cursor-left-word=Control+Left Mod1+b
cursor-right=none
# cursor-right-word=Control+Right Mod1+f
# cursor-home=Home Control+a
# cursor-end=End Control+e
# delete-line=Control+Shift+BackSpace
delete-prev=BackSpace
# delete-prev-word=Mod1+BackSpace Control+BackSpace Control+w
# delete-line-backward=Control+u
# delete-next=Delete KP_Delete Control+d
# delete-next-word=Mod1+d Control+Delete Control+KP_Delete
delete-line-forward=none
prev=Up Control+k
# prev-with-wrap=ISO_Left_Tab
prev-page=Left Control+h
# next-with-wrap=none
next-page=Right Control+l
# expunge=Shift+Delete
# clipboard-paste=Control+v XF86Paste
# primary-paste=Shift+Insert Shift+KP_Insert

