# commands go through bash
shell = "bash -c '{}'"

[[items]]
template = "foot"
subtemplate = "default"
file = "~/.config/foot/foot.ini"
start = "# flavours start"
end = "# flavours end"

[[items]]
template = "fuzzel"
subtemplate = "default"
file = "~/.config/fuzzel/fuzzel.ini"
start = "# flavours start"
end = "# flavours end"

[[items]]
template = "neovim"
subtemplate = "default"
file = "~/.config/nvim/lua/config/theme.lua"
rewrite = true

[[items]]
template = "lualine"
subtemplate = "default"
file = "~/.config/nvim/lua/lualine/themes/default.lua"
rewrite = true

[[items]]
template = "waybar"
subtemplate = "default"
file = "~/.config/waybar/style.css"
rewrite = true

