[main]
font=FiraCode Nerd Font:size=14

# crunchy forest
[colors]
alpha=0.9
background=000f05
foreground=dbffdb

regular0=000f05
regular1=694125
regular2=236b3e
regular3=967e53
regular4=62b196
regular5=8f8072
regular6=409860
regular7=c5f09f

bright0=0b2a23
bright1=ff0000
bright2=00ff00
bright3=ffff00
bright4=00ffff
bright5=ff00ff
bright6=80c884
bright7=dbffdb

